x=1
print(x)
print(type(x))
x=0.1
print(type(x))
x=True
print(type(x))
a=input("请输入:")
int(a)
print(a)
float(a)
print(a)
price=input("苹果价格: ")
weight=input("苹果重量: ")
price_f=float(price)
weight_f=float(weight)
money=price_f*weight_f
print(money)
price=float(input("请输入价格: "))
print("我的名字叫 %s,请多多关照" % name)
print("我的学号是 %06d" % student_no)
print("苹果单价 %.02f 元/斤, 购买 %.02f 斤, 需要支付 %.02f 元" % (price,weight,money))
print("数据比例是%.02f%%" % (scale * 100))
name=input("请输入姓名:")
company=input("请输入公司: ")
title=input("请输入职位: ")
phone=input("请输入电话: ")
email=input("请输入邮箱: ")
print("*"*50)
print(company)
print()
print("%s (%s)" % (name,title))
print()
print("电话: %s" % phone)
print("邮箱: %s" % email)
print("*"*50)